[package]
name = "gcau_cal0"
version = "1.0.0"
authors = ["G. Gauthier <gerard.m.gauthier@free.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
regex = "1.5.4"
serialport = "4.0.0"
